5 minutes to numpy
==========================

In [1]:
# Python's list is useless for numerical computation!
a = [0.1,  0.2,  0.3]
b = [1.0,  2.0,  3.0]
c = a + b
print(c)

[0.1, 0.2, 0.3, 1.0, 2.0, 3.0]


In [2]:
# Let's use numpy!
import numpy as np

a = np.array([0.1, 0.2, 0.3])
b = np.array([1.0, 2.0, 3.0])
c = a + b
print(c)

[1.1 2.2 3.3]


In [3]:
# The array indices begins 0.
print( c[0], c[1], c[2] )
print( c.shape )
print( c.size )

1.1 2.2 3.3
(3,)
3


In [4]:
# Inner product
print("a =", a)
print("b =", b)
z = a[0]*b[0] + a[1]*b[1] + a[2]*b[2]
print( z )

z = a.dot(b)
print("Dot product of a and b is", z)

a = [0.1 0.2 0.3]
b = [1. 2. 3.]
1.4
Dot product of a and b is 1.4


In [5]:
d = a
print(d)

# d is not a copy but a 'view' of a
d[0] = 99
print("d = ", d)
print("a = ", a)

[0.1 0.2 0.3]
d =  [99.   0.2  0.3]
a =  [99.   0.2  0.3]


In [6]:
# 2d array as a matrix?
ma = np.array( [[20.03,  20.13,  20.23],  [21.03,  21.13,  21.23]] )
print(ma)

print("The shape of ma is", ma.shape[0], "by", ma.shape[1])

x = ma[0,2]
print("ma[0,2] is", x)

[[20.03 20.13 20.23]
 [21.03 21.13 21.23]]
The shape of ma is 2 by 3
ma[0,2] is 20.23


In [7]:
# Matrix transposition (view)
mb = ma.T
print(mb)

print("The shape of mb is", mb.shape[0], "by", mb.shape[1])
mb[2,0] = 9999
print(ma)

[[20.03 21.03]
 [20.13 21.13]
 [20.23 21.23]]
The shape of mb is 3 by 2
[[  20.03   20.13 9999.  ]
 [  21.03   21.13   21.23]]


In [8]:
# Extract a row as an array
q = ma[1, :]  # the 2nd row
print(q)

[21.03 21.13 21.23]


In [9]:
# Extract a column as an array
p = ma[:, 0]    # the 1st column
print(p)

[20.03 21.03]


In [10]:
# Extract columns as a 2d array
r = ma[:, [0,2]]  # the 1st and 2nd columns
print(r)

[[  20.03 9999.  ]
 [  21.03   21.23]]


In [11]:
# Identity matrix
me = np.eye(3)
print(me)

# Zero matrix
siz = (3,5)  # tuple
m0 = np.zeros(siz)
print(m0)

# Ones matrix
m1 = np.ones((3,2))
print(m1)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
[[1. 1.]
 [1. 1.]
 [1. 1.]]


In [12]:
# elementwise multiplications
mh = m1 * 0.5
print(mh)
print(mh * mh)

[[0.5 0.5]
 [0.5 0.5]
 [0.5 0.5]]
[[0.25 0.25]
 [0.25 0.25]
 [0.25 0.25]]
